### ISSUE TITLE
Right manner to use conns & pools & uv loops & threads

### ISSUE THREAD

**Issue by eladn** [libattachsql/libattachsql#195]
I'm currently writing a server application working with libuv. It's events are running on the main thread loop. I would like to understand what would be a good practice to integrate libattachsql.
1. I've noticed that each pool has it's own uv loop (is that correct?). Hence, I guess there is no idea having multiple pools running on the same thread as shown in the example (because I'll have to run those loops one-after-one). Is that correct? What is the right practice to allocate threads accordingly & distribute the pools across threads? (one thread per pool?)
2. In what cases should I consider having more than one pool?
3. Using the given library interface, the uv loop is created & freed internally by the library, and particularly, one cannot set manually the uv loop of a certain connection/pool to be an external (already exists) uv loop. What is the idea standing behind this design? What possible difficalties would I face if I were to modify the library so it can do so? (so that my server's main loop would also serve a connections pool of libattachsql)
4. Is there a known & effective way to maintain right number of connections in respect to a given number of incoming queries per second?
5. How could you describe the overhead of having many connections? (conn per query for example)

**Comment by LinuxJedi** [comment]
Hi eladn,

First I should note that 2.0 is not well tested, at best is should be considered alpha and I haven't done any work in libattachsql for over a year.

Now to your questions:

1. With 2.0 that is correct. The examples need updating and work on the pool handling is not yet complete. One thread per pool was my intention.

2. If you have a client connecting to more than one group of database servers.

3. I had a request a long time ago to open up access to the uv loop via the API. Off the top of my head I can't think of any immediate issues with this but it has been a while since I've looked at the code.

4. Not yet, if I had continued the project I would have done more work on this.

5. Apart from the initial handshake the overhead should be minimal, the library was also designed to be lightweight in terms of memory allocations per connection too. During my own testing I'm not sure if I went over 512 connections though. I did a blog post about it a long time ago: https://linuxjedi.co.uk/posts/2014/Oct/15/libattachsql-single-thread-vs-libmysqlclient-multi-thread/

I hope this helps. It was a good project, I enjoyed working on it. Unfortunately I don't have time to continue working on it any more.

**Comment by eladn** [comment]
Thanks! Do you know any similar library that works asynchronously with libuv?
Btw, when you have some free time, it would be great if you could write down a few issues here to describe the next steps that should be done with the library according to your vision with respect to the current state. In that way contributors would be able to continue the great work you've done :)

**Comment by LinuxJedi** [comment]
I'm not aware of any C libraries that use libuv. There are a few other async ones out there such as MariaDB's C connector.
All the plans I remember are already in the GitHub issues. Everything else was lost when I left HP unfortunately.
I believe my general direction was to model it similar to async MySQL libraries in other languages which is why I was developing the pool code in the direction it was heading.
